### ISSUE TITLE
Universal links with iOS not working.

### ISSUE THREAD

**Issue by babulpatel1309** [llfbandit/app_links#1]
### Steps to reproduce

1. Created **apple-app-site-association** file with appropriate content.
2. Pasted it in .well-known directory as per the requirements
3. Updated code from xcode to support associated domains
4. Sent an verification email to verify the universal link
5. Clicked on verify email which took me to Safari instead of installed application

apple-app-site-association file content
```

{
    "applinks": {
        "apps": [],
        "details": [{
            "appID": "TEAMID+BUNDLE_ID",
            "paths": ["*"]
        }]
    }
}
```

> iOS version: 14.1

**Comment by llfbandit** [comment]
Well, there's almost no code in this package...

Are you sure about those requirements?
- HTTPS usage
- https://yourdomain.com/.well-known/apple-app-site-association is accessible without any redirection?
- Did you enabled `Associated Domains` capability in your provisioning profile?

In your ios/Runner/Runner.entitlements, does the xml look like this?
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
	<key>com.apple.developer.associated-domains</key>
	<array>
		<string>applinks:*.yourdomain.com</string>
	</array>
</dict>
</plist>
```
