### ISSUE TITLE
Both getInitialAppLink and onAppLink get called on iOS

### ISSUE THREAD

**Issue by duzenko** [llfbandit/app_links#10]
I encountered this issue when trying to add support for app links to our flutter app
This happens when app is stopped and cold started with an app link
On Android getInitialAppLink() returns the incoming link and we use that to open a route inside the app
On iOS, however, additionally onAppLink() gets called, as if two separate links were arriving
This is very confusing, leading to navigation mixups and errors

Please advise

**Comment by duzenko** [comment]
Test log

Android 
![image](https://user-images.githubusercontent.com/1481807/134469692-11ad3697-ea80-435c-9a25-d1ba299c8b2d.png)

iOS
![image](https://user-images.githubusercontent.com/1481807/134471469-7aa52efc-08bd-4453-8c30-e663fae201d3.png)

**Comment by llfbandit** [comment]
Thanks for the report. Looking into it.

**Comment by andirihs** [comment]
I'm facing the same issue. Any news?

**Comment by llfbandit** [comment]
Sorry for the delay, it should be fixed in 2.2.1

**Comment by llfbandit** [comment]
Sorry, this was not fixed in 2.2.1. Now it should be in v3.

**Comment by appinteractive** [comment]
> Sorry, this was not fixed in 2.2.1. Now it should be in v3.

hey @llfbandit I see that you did not tag the latest 3.0.0 andf 3.0.1 here on github!?

**Comment by llfbandit** [comment]
Yes it is... But no github release

**Comment by lucasvps** [comment]
I can still reproduce the error, any help?
