### ISSUE TITLE
bitsdojo package compatibility or documentarion

### ISSUE THREAD

**Issue by filipenanclarez** [llfbandit/app_links#100]
Hi, 

I have some problems using your package to handle deep links on windows.

After many tests, i found the problem is a compatibility with [bitsdojo_windows](https://github.com/bitsdojo/bitsdojo_window)package related.

Can you help me, with some doc, about how configure windows file to work with [bitsdojo_window](https://github.com/bitsdojo/bitsdojo_window)package together?

https://github.com/bitsdojo/bitsdojo_window/issues/255

**Comment by llfbandit** [comment]
I'm not sure there's a relation with this package.
Version 4.0.0 has just been released with an updated setup for Windows. This should help.
