### ISSUE TITLE
Query coming in from history.

### ISSUE THREAD

**Issue by Imgkl** [llfbandit/app_links#105]
**Describe the bug**

- Open a app link
- print it.
- Now restart the app
- `getInitialAppLink` is getting triggered with the previous session's history.

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[] Universal Links (iOS)  
[x] or Custom URL schemes? (iOS)  

**Does the example project work?** - Same issue on Example app as well. 

[ ] Yes  
[x] No  
[ ] Irrelevant here 

**Did you fully read the instructions for the targeted platform before submitting this issue?** Yes.

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[x] Irrelevant here

**Comment by llfbandit** [comment]
You mean you use hot restart? If so, there's nothing to do here, there's no way I'm aware of to detect hot-restarting.
Your users won't hot restart your app.

**Comment by Imgkl** [comment]
No, even in the case of terminating the app and re-opening the app triggers the `getInitialAppLink` with previous session's data

**Comment by llfbandit** [comment]
This should be fixed on all platforms with version 6.0.
