### ISSUE TITLE
In hybird app, AppLinks not detected unless registered with FlutterActivity

### ISSUE THREAD

**Issue by kubiakn** [llfbandit/app_links#109]
**Describe the bug**

I'm working on a hybrid app thats transitioning to using AppLinks. The first activities to load including the one that currently has the deeplinks registered to them are not derived from a FlutterActivity. My FlutterActivity is opened post login. Unless I change the registration over to the Flutter Activity in the manifest then AppLinks doesn't pick up any of the deeplinks. But switching to the FlutterActivity changes the stack structure of our app. It would be ideal if i didn't have to change the manifest and just could initialize whatever i need to on the flutter side to get AppLinks to work in the non-flutter activity. I tried manually registering the plugins when i start up the flutter engine but that's not working. Is this possible?

**Does it related to**

[X] App Links (Android)  
[X] Deep Links (Android)  
[ ] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[ ] No  
[X] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[X] Irrelevant here

**Comment by llfbandit** [comment]
There's no way for the plugin to be aware of your registered activity. Worse, the engine may be not started at all so as the plugin.
From plugin perspective, the Flutter plugin API only provides its own activity from where we can handle new intents.
