### ISSUE TITLE
Support for Google Play deferred deeplinking?

### ISSUE THREAD

**Issue by duzenko** [llfbandit/app_links#11]
Do you support applinks passed through Google Play when installing the app?
We're using Adjust DeepLinking platform to generate links, but don't receive the applink on first run after install.
I think it's described in https://developer.android.com/google/play/installreferrer/library

**Comment by llfbandit** [comment]
I'm not sure to follow you on this.
`Install Referrer Library` purpose is to get some details on installed app.
As far as I can see, there's no relation with deep linking.

Do you need to retrieve `installReferrer` URL?

AppLink is managed by Android system. So Google Play or whatever is the source of the request, it should work.

**Comment by duzenko** [comment]
Did you ever get the referrer url to propagate to flutter via app_links interface? I tested it and it does not appear to work

**Comment by duzenko** [comment]
Do we need to add `action="com.android.vending.INSTALL_REFERRER"` receiver or something?

**Comment by duzenko** [comment]
This is what I get after I open the app from Play after installing it
![image](https://user-images.githubusercontent.com/1481807/134512125-13e5c5bf-5ab0-4b6f-8a87-9510303d02d2.png)

**Comment by llfbandit** [comment]
Sorry but `Install Referrer Library` is not part of the package, this is out of scope.

**Comment by SuhailJafrinmk** [comment]
Is there any updates regarding this can i get the applinks passed through Google Play when installing the app or do i have to install the "install_referer" library ?
