### ISSUE TITLE
DeepLinks Issue in Linux.

### ISSUE THREAD

**Issue by aarshman-mufin** [llfbandit/app_links#110]
I integrated the app_links properly in the desktop application and it is working fine with Windows and macOS.
I created the .deb installer with [Flutter Distributor](https://pub.dev/packages/flutter_distributor ).
I added some postInstall scripts to create a .desktop file and place it in `~/.local/share/applications/`
The post_install scripts ran successfully, i also executed the command `update-desktop-database ~/.local/share/applications/`
I checked the scheme with `xdg-mime default yourapp.desktop x-scheme-handler/yourcustomscheme`
It showed the scheme and it was properly configured.

The only thing that was not working was `xdg-open yourcustomscheme://test`
When i opened the url which i wanted to be captured, i did got a prompt to open with xdg-open but upon clicking open, the application didn't captured the link but i was able to see it in the console.

`gio: mustmate://login: The specified location is not supported,`

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[ ] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  
[ ✔️] or Custom URL schemes? (Linux)  

**Does the example project work?**

[ ] Yes  
[ ] No  
[ ✔️] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?** 
**Yes**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[✔️ ] Irrelevant here

**Comment by aarshman-mufin** [comment]
Anyone has faced this issue? or got a workaround for this?

**Comment by llfbandit** [comment]
I'm not familiar with Linux but Linux code was refactored in version 6.0. It may worth a try.

**Comment by liquidiert** [comment]
Hey @aarshman-mufin did you check your exec path is correct?

**Comment by llfbandit** [comment]
Yes, please fill a PR to improve docs. I don't have Linux.
