### ISSUE TITLE
Specific Link No Longer Works on macOS using Safari

### ISSUE THREAD

**Issue by tmfdouglas** [llfbandit/app_links#114]
**Describe the bug**

I previously use a specific string as my deep link and it was working fine when opened through Safari, however on macOS it suddenly stopped working but other strings still do work when using Safari.  The problematic string works fine from Chrome.

I tested with the example app from this repo and can reproduce the same behaviour, the app works as expected using the link in the example via Safari and any other link I change it to expect for the specific one causing a problem.

I assume this issue is specific to my machine and I could work around it by changing the link in the app or using Chrome however I'm keen to understand why this is happening.

Apologies but I can't provide a test case as the example app works fine except for with one specific string when using Safari (that string also works fine on Windows).

When I use the link in a Safari I get the usual box saying "Do you want to allow this website to open..." and then when I click yes I get a pop up box with the finder image saying "The application ... can't be opened" and an Ok button to dismiss.

Any thoughts would be much appreciated!

My concern is that one the app is published if this happens on a users machine then it's a more major problem.

Thanks!

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[ ] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

macOs

**Does the example project work?**

[ ] Yes  
[ X ] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Yes - and it works fine, except for with one specific string on one machine.

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[ X ] Irrelevant here

**Comment by llfbandit** [comment]
Web support is very limited.
There's not much inside, I only take the `window.location.href` as initial link and propagate it to Flutter app.

The issue seems to be specific to Safari in whatever version not this package.
