### ISSUE TITLE
App link just open browser instead of app.

### ISSUE THREAD

**Issue by lethanhtan89** [llfbandit/app_links#116]
Hello everyone,

I have a issue that I followed all document on pub.dev but I can not open app when clicked to link, it just show browser on Android app links.

This is my config 
              

>           <intent-filter` android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />
                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />
                <data android:scheme="http"/>
                <data android:scheme="https"/>
                <data android:host="mydomain.web.app"/>
                <data android:pathPrefix="/product" />
            </intent-filter>

Please give me a solution if there is any.

Thank you so much.

**Comment by llfbandit** [comment]
Read the documentation please.
