### ISSUE TITLE
Other packages are not receiving custom URLs

### ISSUE THREAD

**Issue by mbkim95** [llfbandit/app_links#120]
**Describe the bug**

Hello. I'm an maintainer of [kakao_flutter_sdk](https://github.com/kakao/kakao_flutter_sdk) plugin.
This plugin provides a number of features specific to the KakaoTalk app (South Korea's messenger service)
Typically, It provide login throught the KakaoTalk app.

I'm experiencing issues when using app_links and kakao_flutter_sdk together, so I was wondering if you could look into this.

kakao_flutter_sdk get authorization code via the `application(_:open:options)` method when handling login in the iOS. (url is `kakao${app_key}://oauth?code=${authorization_code}`)
However, [The `application(_:open:options)` method in app_links is returning true](https://github.com/llfbandit/app_links/blob/ef67cef1ddff1ce96344c9d54893163234a67b15/ios/Classes/SwiftAppLinksPlugin.swift#L90), so `application(_:open:options)` method in kakao_flutter_sdk is not being called.

The kakao_flutter_sdk doesn't seem to be able to handle this issue, and I didn't find a solution in the app_links guide. 
Could you please let me know if there is a way to resolve this issue, and also explain why you changed the return value of `application(_:open:options)` in app_links to true. (I have read the [changelog](https://pub.dev/packages/app_links/changelog)) Or maybe you could modify the return value of `application(_:open:options)` to false?

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[ ] Universal Links (iOS)  
[x] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[] No  
[x] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[x] Irrelevant here

**Comment by llfbandit** [comment]
You're right, since we're all isolated from each other there's no possibility per plugin to workaround this. That was a bad decision on my side.
I'll release soon a new version reverting this behaviour change to ease usage.

**Comment by llfbandit** [comment]
Change has been reverted in 6.0.2.
