### ISSUE TITLE
Only the latest stream listener receives events

### ISSUE THREAD

**Issue by OutdatedGuy** [llfbandit/app_links#123]
**Describe the bug**

I have setup two different stream listeners on two different pages in my application. These are required so perform different tasks depending upon which App/Universal link is opened.

However, only the stream listener that is setup later (on the 2nd page) receives all the events. And the 1st one does't get any.

```dart
AppLinks().uriLinkStream.listen(_handleAppLink);
```

**Does it related to**

- [x] App Links (Android)  
- [ ] Deep Links (Android)  
- [x] Universal Links (iOS)  
- [ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

- [ ] Yes  
- [ ] No  
- [x] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Yes.

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

- [ ] Yes  
- [ ] No  
- [x] Irrelevant here

**Comment by llfbandit** [comment]
AppLinks is singleton. From here, you can wrap it and publish the stream as a broadcast stream or/and create as many filtered streams you need.

`AppLinks().uriLinkStream.asBroadcastStream()`

**Comment by OutdatedGuy** [comment]
Thanks for the info. However, now I have to create and maintain my own stream now.

Can we get a `AppLinks().uriLinkBroadcastStream` method that listens to `AppLinks().uriLinkStream`?
