### ISSUE TITLE
URLs with multiple query params got only first param 

### ISSUE THREAD

**Issue by Md-Abdul-Halim-Rafi** [llfbandit/app_links#13]
URLs like this format `https://example.com/test?id=123&name=hello&anotherParam=world` 
is only showing `https://example.com/test?id=123`

Can't access all query parameters. Getting only the first one.

**Comment by llfbandit** [comment]
Thanks for the report, I guess this is only an issue with adb?
In my own apps, it works fine.

**Comment by golane-august** [comment]
See: https://stackoverflow.com/questions/35645414/android-deep-linking-with-multiple-query-parameters, need a backslash `\` before & sign.
