### ISSUE TITLE
Function to remove the initial link

### ISSUE THREAD

**Issue by JoepHeijnen** [llfbandit/app_links#130]
**Is your feature request related to a problem? Please describe.**
We are using OAuth for login. After logging in, we no longer need to use the link. Unfortunately, `_appLinks.getInitialLink()` continues to return the OAuth URL, which is not the desired behavior.

**Describe the solution you'd like**
Is it possible to have a function that removes the initial link, so that `_appLinks.getInitialLink()` returns null if the app decides to?

**Comment by llfbandit** [comment]
This is very unclear.

`getInitialLink` will always return the very first link.
Why are you using it explicitly? You can subscribe to the stream and cancel the subscription once you're logged-in.
