### ISSUE TITLE
Wasm support

### ISSUE THREAD

**Issue by nietsmmar** [llfbandit/app_links#131]
**Describe the bug**

I can't built my app for wasm because this package is not supporting it. As it is stable in flutter now, it would be nice if it is supported.

**Comment by llfbandit** [comment]
It is supported since v4.0.0
https://github.com/llfbandit/app_links/blob/master/CHANGELOG.md#400

Unless you provide the line(s) which lead to your build failure, this issue will be closed.

**Comment by flowhorn** [comment]
This seems to be a regression with the linux gtk plugin, I also can't compile to wasm anymore.

I get the following error message:

../../../.pub-cache/hosted/pub.dev/gtk-2.1.0/lib/src/gtk_settings_real.dart:2:1: Error: 'dart:ffi' can't be imported when
compiling to Wasm.
import 'dart:ffi' as ffi;

So the app_links_linux part might cause the issue. I guess a conditional import might help.

**Comment by nietsmmar** [comment]
Ahh it is this issue: https://github.com/dart-lang/sdk/issues/55948

It just got fixed but takes some time to reflect in the flutter version.
