### ISSUE TITLE
app_links_platform_interface v1.2.0 breaks dependencies

### ISSUE THREAD

**Issue by groksrc** [llfbandit/app_links#135]
**Describe the bug**

When v1.2.0 of app_links_platform_interface was published it caused a compiler error in my Flutter project. My project does not take a direct dependency on the app_links_platform_interface library.

**Does it related to**

In order to fix this for now I have to set a manual dependency override as my app does rely on app_links: 3.4.1:

```
dependency_overrides:
  app_links_platform_interface: 1.1.0
```

[x] App Links (Android)  
[ ] Deep Links (Android)  
[x] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[ ] No  
[x] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[x] Irrelevant here

**Comment by llfbandit** [comment]
Arghh sorry about that.

To better understand why didn't you upgrade app_links for more than a year?

**Comment by groksrc** [comment]
I am using FlutterFlow and they manage this dependency. It only upgrades if they upgrade it, usually with a flutter version bump.

**Comment by llfbandit** [comment]
This has been fixed but it's too late, pub.dev doesn't allow to fully remove a version after publication.
