### ISSUE TITLE
Version 6.1.3 does not work on Linux

### ISSUE THREAD

**Issue by CaptainDario** [llfbandit/app_links#138]
**Describe the bug**

The plugin causes the app to raise an exception on Linux.

`MissingPluginException (MissingPluginException(No implementation found for method getInitialAppLink on channel com.llfbandit.app_links/messages))`

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[ ] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[x] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[x] Irrelevant here

**Comment by llfbandit** [comment]
When syncing your dependencies, has `app_links_linux` been pulled ? You can check this in pubspec.lock.

**Comment by llfbandit** [comment]
My bad there's a typo in method name.

**Comment by llfbandit** [comment]
app_links 6.1.4 should fix the issue.
