### ISSUE TITLE
Example Testing

### ISSUE THREAD

**Issue by blondie63** [llfbandit/app_links#139]
I've cloned locally this app_links repo
I just have a validated domain:
 <img width="1156" alt="Screenshot 2024-07-05 alle 14 56 12" src="https://github.com/llfbandit/app_links/assets/1261851/61a9f575-ed15-4a53-b09a-3ef53e55db4f">

I've set a my app name that just have associated domains enabled for iOS and i added domain names using xcode

**Does it related to**

[x] App Links (Android)  
[ ] Deep Links (Android)  
[x] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[x] Yes  
[ ] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[x] Yes  
[ ] No  
[ ] Irrelevant here

Running app, both iOS & Android, app start and show the test messages

I've a NFC token just programmed with link like this:
https://dev-backend.presenzeincloud.com/session/78bcc75f62c011d2ed0dffaced388f0d18e98531

when i scan it by os a browser will be open instead test app !

what's wrong or missing on my steps?

Thanks for help

**Comment by llfbandit** [comment]
You did not mention if your link is working without NFC scanning.
Opening your app from NFC source is an additional layer. To be able to open your app from this source, you must enable NFC feature on Android and iOS platform.
Here's a link for android https://developer.android.com/develop/connectivity/nfc/nfc#ndef-disc

**Comment by blondie63** [comment]
> You did not mention if your link is working without NFC scanning. Opening your app from NFC source is an additional layer. To be able to open your app from this source, you must enable NFC feature on Android and iOS platform. Here's a link for android https://developer.android.com/develop/connectivity/nfc/nfc#ndef-disc

What do you mean by "link that works without NFC scanning"?
To test my server settings I use these two sites:
https://branch.io/resources/aasa-validator/
https://developers.google.com/digital-asset-links/tools/generator?hl=it

and my domain is: dev-backend.presenzeincloud.com

Thanks

**Comment by llfbandit** [comment]
Sorry I misread the description.
Unfortunatly there's not much you can do in this situation.
Browsers may or may not forward links to system, I know that Firefox has a setting to enable/disable this.
