### ISSUE TITLE
Windows: cannot open source file "app_links/app_links_plugin_c_api.h"

### ISSUE THREAD

**Issue by ddomnik** [llfbandit/app_links#142]
I am not sure if this is a bug or maybe a misunderstanding caused by the documentation. If the latter, the documentation should be extended in my opinion to help flutter beginners.

For the Windows Setup it says:

> Add this inclusion in <PROJECT_DIR>\windows\runner\main.cpp
>` #include "app_links/app_links_plugin_c_api.h"`

but VS Code cannot find  "app_links/app_links_plugin_c_api.h", event after the package has been installed via the pubspec.

Instead, it is required to manually copy the source files found in https://github.com/llfbandit/app_links/tree/master/app_links into our flutter project. E.g. if I want to support Windows, I need to copy the "windows" folder into the root of my project.

**Comment by llfbandit** [comment]
You don't have to copy anything. But you need to enable Windows platform on your project first of course.
