### ISSUE TITLE
Window closing errors on Manjaro linux

### ISSUE THREAD

**Issue by daniel1414** [llfbandit/app_links#146]
**Describe the bug**

There are errors when hitting the close window button on Manjaro linux (latest version)

** (test_app:8866): CRITICAL **: 12:42:18.530: void fl_renderer_make_current(FlRenderer *): assertion 'FL_IS_RENDERER(self)' failed

** (test_app:8866): CRITICAL **: 12:42:18.530: void fl_renderer_cleanup(FlRenderer *): assertion 'FL_IS_RENDERER(self)' failed

(test_app:8866): GLib-GObject-CRITICAL **: 12:42:18.534: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(test_app:8866): GLib-GObject-CRITICAL **: 12:42:18.534: g_object_freeze_notify: assertion 'G_IS_OBJECT (object)' failed

(test_app:8866): Gtk-CRITICAL **: 12:42:18.534: gtk_widget_has_default: assertion 'GTK_IS_WIDGET (widget)' failed

(test_app:8866): Gtk-CRITICAL **: 12:42:18.534: gtk_widget_get_receives_default: assertion 'GTK_IS_WIDGET (widget)' failed

(test_app:8866): GLib-GObject-CRITICAL **: 12:42:18.534: g_object_notify: assertion 'G_IS_OBJECT (object)' failed

(test_app:8866): Gtk-CRITICAL **: 12:42:18.534: gtk_widget_has_default: assertion 'GTK_IS_WIDGET (widget)' failed

(test_app:8866): GLib-GObject-CRITICAL **: 12:42:18.534: g_object_thaw_notify: assertion 'G_IS_OBJECT (object)' failed

(test_app:8866): GLib-GObject-CRITICAL **: 12:42:18.535: g_object_unref: assertion 'G_IS_OBJECT (object)' failed

**Does the example project work?**

[ ] Yes  
[ ] No  
[ ✅ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**
Yes

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[ ✅ ] Irrelevant here

The app hangs and doesn't quit properly

![image](https://github.com/user-attachments/assets/a5ca1d18-1188-421c-b4c9-a245490b1518)

**Comment by llfbandit** [comment]
How is it related to this package?

**Comment by daniel1414** [comment]
This happens only when I modify a barebones flutter project with the app_links config steps for linux https://github.com/llfbandit/app_links/blob/master/doc/README_linux.md
Not even touching the flutter project, just my_application.cc

**Comment by llfbandit** [comment]
I'm unable to reproduce this with my linux VM (Ubuntu).
Did you tested it with the example project?

**Comment by daniel1414** [comment]
I used Flutter's example project and added the linux changes to my_application.cc, as I hadn't seen the example project. I've just downloaded and ran it and it works fine on my machine. I'll take a closer look into it when I have some time (probably over the weekend) and look what I've done wrong :)

**Comment by daniel1414** [comment]
Looks like I'm hitting https://github.com/flutter/flutter/issues/144873
