### ISSUE TITLE
Support for a wider range of URIs on Windows.

### ISSUE THREAD

**Issue by twinstar6980** [llfbandit/app_links#149]
In the [current implementation](https://github.com/llfbandit/app_links/blob/445b499f337b2128db4eb04059521042f2ca5df9/app_links/windows/app_links_plugin.cpp#L63C3-L63C40), on Windows, app_links will only treat argv[1] that matches `<scheme>://...` as a URI.
However, according to [rfc 39866](https://datatracker.ietf.org/doc/html/rfc3986#section-3), URIs do not always contain '/' and '//'. The following URIs are also valid:
![image](https://github.com/user-attachments/assets/d9860c01-e852-41e1-b1a8-f034cf36a340)
Should the regex be changed from `^\w+://` to `^\w+:`?
btw, on iOS, as long as the URL contains a single slash `<scheme>:/<path>`, the app can be launched from Safari.

**Comment by twinstar6980** [comment]
@llfbandit Please push v6.3.1 to pub.dev 🙏

**Comment by llfbandit** [comment]
Done!
