### ISSUE TITLE
Desktop support for MacOS and Windows

### ISSUE THREAD

**Issue by chirag729** [llfbandit/app_links#15]
Is support for these platforms on the roadmap?

**Comment by llfbandit** [comment]
I guess it could be possible for custom protocols (i.e. myapp://something).
http and https must remain dedicated to browsers.

Still, the registration of those will be the responsability of the installers (msi on Windows and dmg on macOS) to allow the unregistration.

**Comment by bdremynoel** [comment]
Windows is now available in 3.1.0.
macOS will be in 3.2.0 in few days hopefully.

**Comment by chirag729** [comment]
@bdremynoel thank you!

**Comment by llfbandit** [comment]
macOS is now available in 3.2.0.
