### ISSUE TITLE
Potential Issue with Link Handling in Flutter Beta Causing Duplicate Triggers in app_links Plugin

### ISSUE THREAD

**Issue by naivetoby** [llfbandit/app_links#152]
### Description

I've encountered a potential issue while running a project demo using the `app_links` plugin on an iPhone simulator. The problem seems to be related to how Flutter Beta handles link events, leading to duplicate triggers.

### Steps to Reproduce

1. Modify the code to add logging:

    ```dart
    onGenerateRoute: (RouteSettings settings) {
        Widget routeWidget = defaultScreen();

        // Mimic web routing
        final routeName = settings.name;

        // Add Log
        debugPrint('routeName: $routeName');

        if (routeName != null) {
          if (routeName.startsWith('/book/')) {
            // Navigated to /book/:id
            routeWidget = customScreen(
              routeName.substring(routeName.indexOf('/book/')),
            );
          } else if (routeName == '/book') {
            // Navigated to /book without other parameters
            routeWidget = customScreen("None");
          }
        }

        return MaterialPageRoute(
          builder: (context) => routeWidget,
          settings: settings,
          fullscreenDialog: true,
        );
    }
    ```

2. Run the following command:

    ```bash
    xcrun simctl openurl booted "app://www.example.com/#/book/hello-world"
    ```

### Expected Behavior

- The logs should display the route name once.

### Actual Behavior

- The logs display the following:

    ```bash
    flutter: onAppLink: app://www.example.com/#/book/hello-world
    flutter: routeName: /book/hello-world
    flutter: routeName: /#/book/hello-world
    ```

It appears that Flutter Beta may have changed the way it listens to links, resulting in the route being triggered multiple times. This issue was observed on both iOS (simulator) and Android devices.

### Environment

- Flutter Version: Flutter (Channel beta, 3.25.0-0.1.pre, on macOS 14.6.1 23G93 darwin-x64, locale zh-Hans-CN)
- Plugin Version: 6.3.1
- Platforms: iOS Simulator, Android Devices

### Additional Information

I am unsure if this is the appropriate place to report this issue, but I have noticed similar behavior on Android as well. Any guidance or fixes would be appreciated.

**Comment by llfbandit** [comment]
Thanks for the feedback. To be sure, you didn't change anything in the example project?
According to your log, it feels like Flutter deep linking is enabled. The example calls the route with fragment only (/book/hello-world) while the last entry shows full path (/#/book/hello-world, just a guess).

This package only provides a bridge to retrieve URIs from native side. While navigation may be a target for apps, what is done with the URI is out of the scope of this package.

**Comment by naivetoby** [comment]
Thank you for your prompt reply.

To clarify, I didn't make any changes to the example project other than adding a single line of logging code:

```dart
debugPrint('routeName: $routeName');
```

Additionally, I updated Flutter to the latest Beta version. The issue I observed occurred right after the upgrade, with no other modifications to the codebase.

Given that this package primarily bridges URIs from the native side, I understand that navigation handling is outside its scope. However, the observed behavior seems to be linked to the way Flutter Beta is processing deep links, possibly due to changes in how it handles fragments in URIs.

You might want to try updating to the latest Flutter Beta and see if you can replicate the issue on your end. It could help determine if there's an unintended interaction between Flutter Beta and how the package retrieves URIs.

Thanks again for your assistance.

**Comment by naivetoby** [comment]
i got it, thinks

https://github.com/llfbandit/app_links/commit/9649162700f55f9265e95256528cd3f07387a13a
