### ISSUE TITLE
New app_links windows integration not functioning as expected

### ISSUE THREAD

**Issue by chirag729** [llfbandit/app_links#154]
**Describe the bug**

I recently updated the integration for my flutter windows app removing the modifications to the .cpp file and following the recommended setup instructions here: https://github.com/llfbandit/app_links/blob/master/doc/README_windows.md

The behaviour is now that when the protocol link is activated on the webbrowser, a new instance of my app is launched, instead of the data being routed to the currently open app.

I'm using this to implement SSO so my app is already open when the protocol link is activated

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[ ] Universal Links (iOS)  
[X] or Custom URL schemes? (Windows)  

**Does the example project work?**

[ ] Yes  
[ ] No  
[X] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[X] Yes  
[ ] No  
[ ] Irrelevant here

**Comment by llfbandit** [comment]
:exploding_head: Wow, sorry about that. I confirm the issue.
Currently updating the docs to revert, modifying main.cpp is still need to enable single instance. I will also publish another version to update previous changelog.

Thanks for the report.

**Comment by chirag729** [comment]
@llfbandit Thanks for the fast response. Quick question, you said that main.cpp needs to be modified but in my previous code that worked I had actually made modifications in the win32_window.cpp, presumably following some older instructions. 

Did the modifications required change at some point?

**Comment by chirag729** [comment]
@llfbandit I also asked questions in the msix package repo: https://github.com/YehudaKremer/msix/issues/279

The developer recommended an alternative method for ensuring single instance: https://github.com/YehudaKremer/smart_watch_widget/blob/main/windows/runner/main.cpp

Would that method work (it seems a bit simpler) or would your changes to the .cpp files still be required?

**Comment by llfbandit** [comment]
This is another way to do it, but we need to get at some point the window handler to post the message to Flutter side on the current instance (not the new one being created).
So finally, nothing changed, this is still required unfortunately.

6.3.2 published. This version does not change anything but the changelog for pub.dev.
