### ISSUE TITLE
iOS Universal Links not working correctly with Flutter 3.24

### ISSUE THREAD

**Issue by Masamichi-Mandai** [llfbandit/app_links#156]
**Describe the bug**

Once I upgraded my application to Flutter 3.24.2 my Universal Links on iOS stopped working. Or at least: they are not working as intended.

I am using app_links version 6.3.2.

Expected behaviour:
Click on universal link opens the app and the appropriate page.

Observed behaviour:
Click on Universal Links opens the app. Quickly after that the native browser is opened with the link as target. In my logs I see a warning "Failed to handle route information in Flutter.".

Downgrading to Flutter 3.22.3 resolved this issue for me.

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[✓] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[✓] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[✓] Yes  
[ ] No  
[ ] Irrelevant here

**Comment by llfbandit** [comment]
Thanks for the report.

It looks like Flutter team has enabled their default deep linking feature by default...
https://github.com/flutter/engine/pull/52350

So, you must refer to docs to disable it explicitly now for [Android](https://github.com/llfbandit/app_links/blob/master/doc/README_android.md) & [iOS](https://github.com/llfbandit/app_links/blob/master/doc/README_ios.md).

**Comment by Masamichi-Mandai** [comment]
Thanks for supporting!!

I solved this problem by adding the following settings to my project.

ios/Runner/Info.plist
```
<key>FlutterDeepLinkingEnabled</key>
<false/>
```
