### ISSUE TITLE
iOS uriLinkStream not receiving any links but showing logs

### ISSUE THREAD

**Issue by dehypnosis** [llfbandit/app_links#16]
Thanks for your hard work.

Here is my situation.
- Use Deep link and App link both
- In app_links 2.2.2 works well as expected
- In app_links 3.0.1
  - android works well for both type links
  - in iOS 15.4.1 (real device), it has a problem.

Initial link works well. But `uriLinkStream` never provide events. But it still shows logs like below..

```
"iOS handleLink: myapp://myapp.com/chats"
"iOS handleLink: myapp://myapp.com/chats"
```

... and finally as a workaround i am using 2.2.2 for now with similar interface.. 
```
    final deepLinkStreamController = StreamController<Uri>.broadcast();
    final appLinks = AppLinks(onAppLink: (uri, str) {
      deepLinkStreamController.add(uri);
    });

    ...

   deepLinkStreamController.stream.listen((link) {
      ...
   });
```

Anyone has same issue?

**Comment by dehypnosis** [comment]
Sorry my mistake. forget it

**Comment by pratik97179** [comment]
@dehypnosis Were you able to resolve the issue? If yes, how?
