### ISSUE TITLE
Deeplinks open both app and browser.

### ISSUE THREAD

**Issue by enescerrahoglu** [llfbandit/app_links#162]
**Describe the bug**

Everything works correctly in iOS 18. In versions lower than iOS 18, deep links first launch the mobile application and redirect to the relevant screen. It then opens the browser and goes to the website.

Redirecting to the App Store is an intentional act; We redirect to the App Store thanks to a script running on the website. This is not a problem.

**Does it related to**

[NO] App Links (Android)  
[NO] Deep Links (Android)  
[YES] Universal Links (iOS)  
[MAYBE] or Custom URL schemes? (iOS)  

**Does the example project work?**

[] Yes  
[] No  
[*] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[*] Yes  
[ ] No  
[ ] Irrelevant here

https://github.com/user-attachments/assets/c50c111b-84d3-44e8-b036-748111d86577

**Comment by enescerrahoglu** [comment]
Redirecting to the App Store is an intentional act; We redirect to the App Store thanks to a script running on the website. This is not a problem.

**Comment by llfbandit** [comment]
Disable default Flutter deep linking?
https://github.com/llfbandit/app_links/blob/master/doc/README_ios.md#ios
