### ISSUE TITLE
Bug Report: Manifest Merger Failed Due to minSdkVersion Conflict

### ISSUE THREAD

**Issue by Gperez88** [llfbandit/app_links#163]
**Describe the bug**

I am encountering an issue while using the `app_links` library in my Flutter project. When trying to build the application, I receive the following error:

```
Execution failed for task ':app_links:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [androidx.lifecycle:lifecycle-livedata-core-ktx:2.7.0] as the library might be using APIs not available in 16.
```

This error indicates that the `minSdkVersion` of my project is set to 16, but the `androidx.lifecycle:lifecycle-livedata-core-ktx` library requires a minimum SDK version of 19.

**Does it relate to**

[x] App Links (Android)  
[x] Deep Links (Android)  
[ ] Universal Links (iOS)  
[ ] Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[x] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

[ ] Yes  
[x] No  
[ ] Irrelevant here  

**Additional Context:**

- **Flutter version:** [insert your Flutter version]
- **app_links version:** [insert the version of app_links you are using]
- **Android SDK version:** [insert your Android SDK version]
- **Gradle version:** [insert your Gradle version]

**Steps to Reproduce:**

1. Create a new Flutter project.
2. Add `app_links` as a dependency in `pubspec.yaml`.
3. Set `minSdkVersion` to 16 in the `build.gradle` file.
4. Attempt to build the project.

**Expected Behavior:**

The project should build successfully without manifest merger errors related to `minSdkVersion`.

**Actual Behavior:**

The build fails due to the manifest merger error.

**Possible Solution:**

It would be beneficial if the `app_links` library or its dependencies could be updated to support a lower `minSdkVersion` or provide alternatives to address this issue.

Thank you for your attention to this matter. I look forward to your response.

**Comment by llfbandit** [comment]
Thanks for your report but minimum API level is already set at 16 on this package.
Be sure to use a corresponding Flutter version if you really need to support this level. (API level 16 = Android 4.1 = <0.1% of registered devices in the world = released in 2012).

Also, `androidx.lifecycle:lifecycle-livedata-core-ktx` is not a dependency of this package.
