### ISSUE TITLE
Missing proguard file

### ISSUE THREAD

**Issue by Take-A-Byte** [llfbandit/app_links#176]
**Describe the bug**
Though the documentation says we should include proguard file, example does not include this file
https://github.com/llfbandit/app_links/blob/master/doc/README_android.md#proguard-rules

**Does it related to**

[ ] App Links (Android)  
[x] Deep Links (Android)  
[ ] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[ ] No  
[x] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[x] Irrelevant here

**Comment by llfbandit** [comment]
This is not what the documentation says.
Those rules are automatically added if you use proguard.
