### ISSUE TITLE
MissingPluginException with web app

### ISSUE THREAD

**Issue by awaik** [llfbandit/app_links#177]
Hello, I can't get the link that used for the opening web app.
Can you please advice how to get it?

I tried the code

`final uri = await _appLinks.getInitialLink();`

and get the exception

`MissingPluginException(No implementation found for method getInitialLink on channel com.llfbandit.app_links/messages)`

**Comment by awaik** [comment]
Forgot to add info
`app_links: ^6.3.2`

Flutter doctor

`
[✓] Flutter (Channel stable, 3.24.5, on macOS 14.6.1 23G93 darwin-arm64, locale en-DE)
    • Flutter version 3.24.5 on channel stable at /Users/mavbook/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision dec2ee5c1f (3 weeks ago), 2024-11-13 11:13:06 -0800
    • Engine revision a18df97ca5
    • Dart version 3.5.4
    • DevTools version 2.37.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/mavbook/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-79915917-b509.11)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 16B40
    • CocoaPods version 1.15.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
`

**Comment by sachin8390** [comment]
Replace the method getInitialLink with getLatestLink

**Comment by llfbandit** [comment]
`flutter pub clean && flutter pub get`
Your project seems to be unsynced.
