### ISSUE TITLE
Facebook app links

### ISSUE THREAD

**Issue by jjsebastianfuertes** [llfbandit/app_links#2]
Does it work with Facebook app links?

**Comment by llfbandit** [comment]
This packages intends to open your own flutter app from your specific links.
If Facebook really uses App Links you won't be able to catch urls since you must provide `assetlinks.json` files on each corresponding domains (same behaviour on iOS).

**Comment by AnhDTN** [comment]
How to open my app from social app like facebook, whatsapp..? I have a domain for the file assetlinks.json, apple-app-site-association
