### ISSUE TITLE
Behaviour different depending of Android Version

### ISSUE THREAD

**Issue by spaquis** [llfbandit/app_links#26]
Hi,
I'm currently using your library for handle firebase dynamic link.
I have detected differents behaviours depending of Android version :
 - Android < 12 => The URI contain the original value of the link : https://blabla.page.link/home
 - Android 12 => The URI contain the "deep link value" so the link related to the web site url (for the case app not installed) : https://website.com
 
 I would like to get always the original value of the link, can you help me ?
 
 Thanks in advance,
 Regards

**Comment by llfbandit** [comment]
Should be resolved in version 3.3.0
