### ISSUE TITLE
getInitialAppLink() allways return null  on windows

### ISSUE THREAD

**Issue by UnluckyY1** [llfbandit/app_links#27]
So Far everything works fine on Android and iOS but when it comes to windows when you lunch the app from URL Scheme  the getInitialAppLink()  is Always return null .

to summarise it's the same issue like #7 but for windows platform
Edit : even with the example app if you start the app from an url scheme getInitialAppLink will always return null on windows platform

**Comment by brennschlus** [comment]
@UnluckyY1 I've slighty changed code to make this work in this MR https://github.com/llfbandit/app_links/pull/31, if you want to test it just write me, I can show how to make it work

**Comment by UnluckyY1** [comment]
@brennschlus I will do some tests and let you know if it works

**Comment by UnluckyY1** [comment]
oh you're right i will try again with the necessary changes and let you know

**Comment by UnluckyY1** [comment]
@brennschlus after fixing app_links_windows dependency, i can confirm that getInitialAppLink() now works 
@llfbandit can you check his PR when you got time 
Thank you guys

**Comment by llfbandit** [comment]
Thanks @brennschlus for the fix.
I will trust you on this one. I'm overloaded since... a while now. Sorry for that.
Merged and published!
