### ISSUE TITLE
[Feature] A single stream for all links

### ISSUE THREAD

**Issue by cachapa** [llfbandit/app_links#30]
Generally when I'm implementing app links, I'm interested in all incoming messages regardless of app state.

It would be nice to have a single stream that combines both initial and ongoing links to make it easier to implement this (I believe) common use case.

Here's my implementation as an extension:

``` dart
extension AppLinkX on AppLinks {
  Stream<Uri> get allLinks async* {
    final initial = await getInitialAppLink();
    if (initial != null) yield initial;
    yield* uriLinkStream;
  }
}
```

**Comment by llfbandit** [comment]
Thanks the contribution.
It will be added in the next release (soon).
