### ISSUE TITLE
iOS: getInitialAppLink always returns null

### ISSUE THREAD

**Issue by ShahinRockstarsIT** [llfbandit/app_links#32]
On iOS cold boot getInitialAppLink or even getLatestAppLink always return null;

```
final uri = await appLinks.getInitialAppLink() ?? await appLinks.getLatestAppLink();
// uri is always null on iOS
```

any fix on this issue?

**Comment by llfbandit** [comment]
Does the example work?
I need more than "it does not work". Please fill a reproducer.

**Comment by ShahinRockstarsIT** [comment]
I have tried to get the initial or latest link on several locations in my app. but it seems always to be null.

```
main(){
 runApp(MyApp())
}


Tree:
 -- MyApp ()
 // I tried in this widget
 -- -- Main ()
 // I tried in this widget
-- -- -- Home ()
 // I tried in this widget

```

**Comment by SAGARSURI** [comment]
Hey, @ShahinRockstarsIT please post a sample app that the author can run or debug and reproduce the error. The above code which you posted is not at all helpful.
