### ISSUE TITLE
MacOS Support and Debugging?

### ISSUE THREAD

**Issue by u382514** [llfbandit/app_links#36]
I cannot seem to get the universal links to work in MacOS. It works fine in an IOS simulator but MacOS just opens up Safari and never asks to open in app or anything else. Any ideas?

**Comment by llfbandit** [comment]
Mac os can only handle custom URL schemes like Windows or such

**Comment by llfbandit** [comment]
Http(s) scheme is reserved on those platforms.

**Comment by sugur** [comment]
Why universal links cannot not to work in MacOS? It just opens up Safari with 403.

**Comment by DmitryGaimaldinov** [comment]
There's an example of handling universal links on macos

https://developer.apple.com/documentation/xcode/supporting-universal-links-in-your-app
