### ISSUE TITLE
return url on iOS and Android 

### ISSUE THREAD

**Issue by MamdRoyalWorld** [llfbandit/app_links#39]
_appLinks.allUriLinkStream.listen((uri) {
    // Do something (navigation, ...)
});

will return the url (https://myapp.com?page=$pageName&id=$id&country=$country), with the data passed in it on(on Android),
but on iOS will return the short url (https//:myapp.page.link/...).

how to get the iOS to return the same url as Android

**Comment by llfbandit** [comment]
I guess you are coming from Firebase Dynamic Links?
If so, you are advised to use their dedicated package for this.
