### ISSUE TITLE
Repo is missing readme file

### ISSUE THREAD

**Issue by guyluz11** [llfbandit/app_links#40]
I saw that there is a readme file in each different project directory, but it is important to have a repo readme as well.

This way we can explain to the developers what to expect in which folder and it is much nicer to arrive at to the repo with a readme than just empty bottom.

**Comment by llfbandit** [comment]
Done indirectly with [afda688](https://github.com/llfbandit/app_links/commit/afda688c26828d02ca377ff73f725acae5db30e0)
