### ISSUE TITLE
We need a way to know if we handled the current url

### ISSUE THREAD

**Issue by kaciula** [llfbandit/app_links#41]
Hi. I can reproduce the issue with the example project. 

1. The app is successfully launched from a deep link
2. I leave the app and either I terminate the app or I wait for the app to be terminated by the OS
3. I open the app again
4. The deep link logic is being triggered again with the same deep link

This impacts the user experience as they do not expect to be taken to a deep link page when opening the app from scratch. Surely there must be a way to clear the deep link history.

**Comment by llfbandit** [comment]
There is no history. This package is all about forwarding intents to flutter side.
Are you sure your app was terminated? On which platform?

**Comment by kaciula** [comment]
You are right. It is not actually terminated, but restarted from VS Code. If the app is truly started from scratch, it does not have the deep link anymore.

Sorry for the confusion.
