### ISSUE TITLE
Is there a way for us to not give the user an option to open a link with deeplink? (in Android)

### ISSUE THREAD

**Issue by BunnyBuddy** [llfbandit/app_links#42]
We have an app that uses App Link for deep linking (its an Ecommerce app) and we don't want the user to see the option of selecting our app to open a particular link when they click on our site's url in their browser. 
Instead we want the user to open that link in the browser as it is and once they land on the site, the user may open any link that leads to our app.

Is this possible ? if it is then how can we achieve it in App_Links as I can't seem to find an option in the documentation.

**Comment by llfbandit** [comment]
This is only pattern setup to achieve your goal. See Android and iOS docs for this. Links are available in readme.md.

This is unrelated with the package itself.
