### ISSUE TITLE
Cannot listen for a uri from a running program on Windown

### ISSUE THREAD

**Issue by Huy-Thai** [llfbandit/app_links#45]
Hello, when I run a sample project, access **sample://foo/#/book/hello-deep-linking** through a browser, and open the already-started program, it doesn't have any changes sent.

**Comment by llfbandit** [comment]
Did you follow the setup for Windows ?
You are not respecting the issue template.

**Comment by KristijanMitrik** [comment]
@Huy-Thai @llfbandit  I am having the same problem. Is there some solution for this problem? 
I followed the procedure for setting up the app for windows completely
