### ISSUE TITLE
URI not clear from listener

### ISSUE THREAD

**Issue by water-user** [llfbandit/app_links#46]
I'm using Android 10, i setup custom schema (water://) and the schema is working perfect, i can open my app from other app by this schema.
The problem is when i redirect to other app with some schema (in my case clal://), then the `appLinks.allUriLinkStream.listen` is calling again for some reason, with the last URI (water://).

I'm using url_launcher package to open other app, here's a snippet of code:
![url_launcher](https://user-images.githubusercontent.com/95235346/222463019-492a4c4a-3873-4bc1-9d65-62e942129521.jpg)

Here's a screenshot of what happened when the `launchUrl` is call (line 288 in the screenshot above):
![app_link_listener](https://user-images.githubusercontent.com/95235346/222463091-0d79301a-6ec6-405a-a5b5-bd43aa9cdda4.jpg)

**Does it related to**

[ ] App Links (Android)  
[X] Deep Links (Android)  
[ ] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[ ] No  
[X] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**
YES

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[X] Yes  
[ ] No  
[ ] Irrelevant here

**Comment by llfbandit** [comment]
Somehow I guess you are subscribing again to the stream.
`allUriLinkStream` always starts by pushing initial link (if any).

**Comment by water-user** [comment]
So how can i reset it?

**Comment by letungcntt** [comment]
> So how can i reset it?

Hi. Do you find the solution fix this problem?

**Comment by mlab817** [comment]
did you guys find the solution to this problem? i want to clear the initialLinks because it messes with go_router when refreshed.

**Comment by OziTFA** [comment]
Any solution for this  @water-user ?
