### ISSUE TITLE
getInitialAppLink() not working on first iOS install from App Store

### ISSUE THREAD

**Issue by evanwherchek** [llfbandit/app_links#50]
Excellent work on this package :)

**Describe the bug**

My use case is users click on a link with a unique query parameter that will be used during sign up for my app. This operation uses `getInitialAppLink()`. Everything seems to be working in development when the app is installed on my device. The link can open the app and get the data with no problem so I try to put it on the App Store. Without the app installed, I click on the link, go to the App Store page, download it, and click continue. When I get to the point where `getInitialAppLink()` should be called, it doesn't get the data. But then when I close the app and open it again with the link, everything seems to work. This issue seems to be related to #14.

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[X] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[ ] No  
[X] Irrelevant here  

Info.plist

```
<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleTypeRole</key>
			<string>Editor</string>
			<key>CFBundleURLName</key>
			<string>Bundle ID</string>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>com.bundle.id</string>
			</array>
		</dict>
	</array>
```

**Comment by artemsorochan** [comment]
Btw, does it work for you on GooglePlay first install?

**Comment by vizakenjack** [comment]
I had the same issue, and found that there is a conflict with this package: https://pub.dev/packages/push

If I remove it, getInitialAppLink() works fine

**Comment by evanwherchek** [comment]
> Btw, does it work for you on GooglePlay first install?

Yes. Google Play first install seems to be working.

**Comment by Atiqrehman3054** [comment]
hi i ask question app_links works in that condition if i want pass this params {planid="s34rfdgr54, name = "nick"}; through app_links but app not install in mobile when i click on link it will route to playstore then get parameters 
this type data will manage app_link???

**Comment by lohitbura07** [comment]
Same Issue . Any Update on this?

**Comment by baraghiffari** [comment]
In my case, both doesn't work on the first install. For android i had to use android_play_install_referrer plugin on a first install, not sure how to do it on ios

**Comment by JosiahThobejane** [comment]
> I had the same issue, and found that there is a conflict with this package: https://pub.dev/packages/push
> 
> If I remove it, getInitialAppLink() works fine

This worked for me. Funny how there were no error/info messages. Thanks for the fix!

**Comment by jkoenig134** [comment]
@llfbandit I have the same issue. Packages `push` and `app_links` are installed. When starting my app from a custom URL scheme the initial App link is never recognized.

**Comment by llfbandit** [comment]
If there's conflict with other package please refer to custom setup.
If the other package always returns true, there's nothing I can do, I already provide workaround but if the other package is called before this one, this is a dead end.

**Comment by jkoenig134** [comment]
@llfbandit is this a bug by the other plugin? Should it return false?

**Comment by llfbandit** [comment]
Through Flutter, each iOS package registers as an application delegate to handle options at start/resume state. From here, we get multiple isolated delegates.

So, to propagate unhandled options (here links) to other packages, **all** packages must return `false` but the concerned package.

**Comment by taniksha-mfy** [comment]
Link is not redirecting to play or app stores , if app is not installed. Please help, how  can I do it.

**Comment by zaid-debug** [comment]
> Link is not redirecting to play or app stores , if app is not installed. Please help, how can I do it.

You can ask the back end/ server side guy, he will make it work for you.

**Comment by taniksha-mfy** [comment]
> > Link is not redirecting to play or app stores , if app is not installed. Please help, how can I do it.
> 
> You can ask the back end/ server side guy, he will make it work for you.

I myself handles backend. If you can help with the process. I can integrate..
