### ISSUE TITLE
Https Scheme Support For Windows

### ISSUE THREAD

**Issue by HAFIZkhan-source** [llfbandit/app_links#51]
Hey, Custom Schemes are working well in the windows app. But How to use the HTTPS scheme for the windows app?

**Comment by llfbandit** [comment]
Http and https are reserved protocols to browsers on desktop platforms. We can't change this.

**Comment by HAFIZkhan-source** [comment]
Yes, But my question is how can we use https deep link using this package in windows app?

**Comment by llfbandit** [comment]
You can't.

**Comment by HAFIZkhan-source** [comment]
Is there any package which support the same?

**Comment by llfbandit** [comment]
Unless you're developing a browser, you can't!

**Comment by DmitryGaimaldinov** [comment]
Is there plans to add https scheme support for windows?
