### ISSUE TITLE
I just need the next passed URL and no historic URLs

### ISSUE THREAD

**Issue by rekire** [llfbandit/app_links#59]
I'm using your plugin for a login flow where I redirect the user back to my app. So when I open the browser I start listening for URL like this

```dart
openBowser();
final uri = await AppLinks().allUriLinkStream.first;
print('Got $uri');
```

The problem is that when I call this code twice, that I get directly the result of the first call. I already asked some Flutter developers and it seems that you need to provide this functionality.

I tested this on MacOS, but I think that should be also on Windows.

**Comment by llfbandit** [comment]
This is because you just keep connecting to the same stream again.

AppLinks should be instanciated only once for all the app instance.
