### ISSUE TITLE
web support

### ISSUE THREAD

**Issue by kiaxseventh** [llfbandit/app_links#6]
hello dear @llfbandit 
thanks for this excellent package

please add support flutter web

**Comment by kiaxseventh** [comment]
Just add the string query in the web url
This can help the developer in the same way as a method on android and iOS 
development in the web version very easily

**Comment by llfbandit** [comment]
This package is not concerned by navigation or routing in any way.
I suggest you to use auto_route or beamer packages for navigation "deep linking" meaning here nested routing.

This package only offers the Uri that triggered your app.

**Comment by kiaxseventh** [comment]
Is this package a alternative to uni_links ? it is true ?

**Comment by bdremynoel** [comment]
Yes it seems

**Comment by kiaxseventh** [comment]
in uni link repository you can see web interface implement
it doesn't working now
but there will be such a thing in the future
https://github.com/avioli/uni_links/tree/master/uni_links_web

**Comment by kiaxseventh** [comment]
what advantages you have over the alternative (uni_links)

**Comment by llfbandit** [comment]
I don't know this package. I guess it acquires the very first link on web platform (when you type in address bar).
It's impossible to process further links.

**Comment by llfbandit** [comment]
Web support has been added in 2.2.0.
