### ISSUE TITLE
It can't catch killed app

### ISSUE THREAD

**Issue by mkbsugita** [llfbandit/app_links#60]
**Describe the bug**

If the app wake up, it can work. But I killed the app it can't work.

```
    final appLinks = AppLinks();
    // Subscribe to all events when app is started.
    // (Use allStringLinkStream to get it as [String])
    appLinks.allUriLinkStream.listen((uri) {
      // Do something (navigation, ...)
      onUrlSchemeUpdate(context, url: uri);
    });

  void onUrlSchemeUpdate(BuildContext context, {required Uri url}) {
    // bla bla ...
  }
```

**Does it related to**

[ ] App Links (Android)  
[o ] Deep Links (Android)  
[o ] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[o ] Yes  
[ ] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[o ] No  
[ ] Irrelevant here

**Comment by BhargavJani** [comment]
are you find the solution?

**Comment by mkbsugita** [comment]
@BhargavJani 
Did you meet same bug?

I guess I should get url from the code of `Decomposed usage` in README.

```
final uri = await _appLinks.getLatestAppLink();
```

**Comment by DennisKragekjaer** [comment]
Same issue here on Android

**Comment by RichardRaue** [comment]
First, thank you for this lib. I appreciate your work. However, we face the same issue as mentioned above: when a user opens the app with a deeplink and the app is created from scratch, `getInitialAppLink()` returns 'null' and the deep linking fails. It works well when app is in background. 

**The behaviour is the same on Android and iOS.**

Here's the code:

### main.dart
```
Future<void> main([List<String>? param]) async {
  WidgetsFlutterBinding.ensureInitialized();
  await firebaseInitializer.initFirebase();
  ...
  runApp(MyApp());
}
```

### main_screen.dart (1st widget)
```
class MainScreen extends ConsumerStatefulWidget {

  @override
    Widget build(BuildContext context, WidgetRef ref) {
    initDeepLinkListeners(context, ref);
    ...
  }

  Future<void> initDeepLinkListeners(BuildContext context, WidgetRef ref) async {
    final _appLinks = AppLinks();
    Uri? initialDeepLink = await _appLinks.getInitialAppLink(); // this is 'null' when app is created fresh; otherwise it works!
    ...
  }
}
```
Is this setup correct?

**Comment by llfbandit** [comment]
I guess not.
- You seem to try to catch the link very lately. The native plaform may have already sent its event.
- `AppLinks` has nothing to do in a build method because there's nothing related to `BuildContext` (even if your use case is to do something with it).

For resolving purpose, move `AppLinks()` intanciation to main function to see if the very first link is now catched.
You can leave you as it is in your example.

**Comment by RichardRaue** [comment]
Thanks for the hint. I tried initializing AppLink as soon as possible:
### main.dart
```
Future<void> main([List<String>? param]) async {
  WidgetsFlutterBinding.ensureInitialized();

  final _appLinks = AppLinks();
  Uri? initialDeepLink = await _appLinks.getInitialAppLink();
  print("INIT with DEEP LINK while CREATED: $initialDeepLink");

```
However, `getAppLink()` still returns `null`.

**Comment by llfbandit** [comment]
Can you just read the comment above yours?

I need to instanciate the plugin early to register it to the engine.
After this, in your flutter app, use it normally.
