### ISSUE TITLE
[Bug] hot reload calls deeplink again

### ISSUE THREAD

**Issue by mkbsugita** [llfbandit/app_links#61]
**Describe the bug**

```
final appLink = await _appLinks.getInitialAppLink();

_linkSubscription = _appLinks.uriLinkStream.listen((uri) {
  myMethod(context, url: appLink ?? uri);
});
```

when I did hot reload it calls deep link again!!!

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[o] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[o] Yes  
[ ] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[o] No  
[ ] Irrelevant here

**Comment by pro100svitlo** [comment]
yep, indeed.

Even worse: 
- I start the app without deep link (no initial link)
- receive deepLink via stream (no initial link)
- do a hot restart
- receive initial link (which is not initial, but the last one received from stream)

**Comment by llfbandit** [comment]
Need to move away initialLink & latestLink to dart code.
A thing to note here, we can't listen to hot restarts because the app is destroyed and re-created.

**Comment by llfbandit** [comment]
I digged into the code tonight and there's nothing I can do for this.
Plugins are not aware of hot reloads or restarts and I must keep initial link on native side to ensure that it will not be skipped at launch from cold state.

Notice that this is not a specific issue on iOS platform, the same happens on Android too.
Anyway, this can occur only on debug sessions.

**Comment by EM-Sabeel** [comment]
I also have the same issue. Is there any fix?
above comment, @llfbandit mentioned a solution but it is not working anymore.
> Need to move away initialLink & latestLink to dart code.
let me know if any other fixes.

**Comment by EM-Sabeel** [comment]
can you provide a reset option to reset the URI?

**Comment by SL-Chinmay** [comment]
I am also getting the same issue still. Is there any fix or workaround for this bug? The app never stops executing getInitialAppLink() when doing hot restarts.

**Comment by xdanaskos** [comment]
Hello all,

I am having the same issue but not only with hot restarts. My issue is that I navigate through the app and then I navigate back to the statefull widget that does the call. Then the getInitialAppLinkis excecuted again and I end up navigating to the same loop.

**Comment by dbeqiraj** [comment]
I had this issue, the stream was emitting the same link over and over again. I came up with this workaround:

```
_linkSubscription = _appLinks.uriLinkStream.distinct().listen((uri) {
  myMethod(context, url: appLink ?? uri);
});
```

Using `distinct()` will not trigger the listener unless the link is a new one.
