### ISSUE TITLE
No implementation found for method getInitialAppLink on channel com.llfbandit.app_links/messages Flutter web.

### ISSUE THREAD

**Issue by naumanmir** [llfbandit/app_links#62]
Hello @llfbandit,

I am trying to implement deep links in flutter web assuming web support is added in V2.2.0 and calling getInitialAppLink() only but getting below exception. 

Uncaught MissingPluginException(No implementation found for method getInitialAppLink on channel com.llfbandit.app_links/messages).

**Comment by llfbandit** [comment]
As always be sure to get package up to date when adding a new package.
If necessary, `flutter clean && flutter pub get`.
