### ISSUE TITLE
Ideas for v4 roadmap

### ISSUE THREAD

**Issue by llfbandit** [llfbandit/app_links#68]
- **Allow to set if the link has been handled or not**:
Some apps need to inform the system if the link has been handled or not for subsequent plugin acting in the same area.
Introduce callback system aside current stream to reach this goal?
Stream "mode" would return link has been handled by the app while callback "mode" could allow a precise result (if feasible, dart methods are marked as asynchronous while it may not be true).

- **Allow multiple instances**:
Strongly discouraged but asked multiple times for specific/scoped scenarios.
Allowing multiple platform instances is out of question, app / plugin is a 1/1 relation. Breaking this, would lead to uncatched events.
Still, by allowing multiple instances on dart side with a stream controller, this could fix hot reload issue during development and cover scoped scenarios.
For scoped scenarios, this would require to add a regex list to supported links. This addition can't fully cover the previous point to inform the system if the link has been handled or not.

Working with those both potential features may lead to unwanted results. In first case, the user wants to react precisely to the system while the second will automatically return the result based on the regex list.

What do you think about those two points?

**Comment by CaptainDario** [comment]
I think the first point could be really useful.

On a side not, could Linux (snap?) support beadded to the v4 roadmap?

**Comment by cartellink** [comment]
@llfbandit I see you closed this as completed, can you please shed some light on the solution and how do we access it?
