### ISSUE TITLE
The scheme with dot(.) symbol doesn't work

### ISSUE THREAD

**Issue by LucasXu0** [llfbandit/app_links#69]
**Describe the bug**

I set up a scheme `io.abc.abc` on the Windows platform; however, it doesn't work.

I tried using `io-abc-abc` instead, and it works perfectly. Does it meet the expectation?

**Does it related to**

- [ ] App Links (Android)  
- [ ] Deep Links (Android)  
- [ ] Universal Links (iOS)  
- [ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

- [ ] Yes  
- [x] No  
- [ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

- [ ] Yes  
- [ ] No  
- [ ] Irrelevant here

**Comment by llfbandit** [comment]
I know that a scheme for URI with this kind of pattern is allowed but I can't say for Windows.
I didn't find any docs related to this.

**Comment by biendltb** [comment]
@LucasXu0 May I ask if you successfully create a supabase redirect to a deep link on Windows?

I have supabase OAuth redirects to a deep link which subsequently launches my app. This setup works well for Linux but it does not work for Windows for some reason. My app does not launch via redirect but I can launch it by typing the deep link directly on the browser's address bar. I wonder if it's a Windows restriction or it's an issue with my packaging config.

I really appreciate it if you could answer my question.
