### ISSUE TITLE
getInitialAppLink on Android, does not work correctly.

### ISSUE THREAD

**Issue by vasilecristian** [llfbandit/app_links#7]
I have an app that can be started from a link on iOS and Android. 
When the app is minimized, i can start it with a link, and the getLatestAppLink catch the link correctly.
Problem:
When the app is closed (aka not minimized) on Android the getInitialAppLink does not return the link.  This problem is only on Android. On iOS it works.

**Comment by llfbandit** [comment]
There's debug logs available in logcat `adb logcat`.
To know if the intent has been triggered on Android you can look for 'com.llfbandit.app_links' tag.

You should see something like:
`handleIntent: (Action) ...`
`handleIntent: (Data) ...`

**Comment by llfbandit** [comment]
I'm unable to reproduce it, is it still relevant on your side?

**Comment by llfbandit** [comment]
Can you provide a reproducer? I use the package for my own needs and myself or my clients don't see any issue on such scenario.

**Comment by alexobviously** [comment]
Same for me - if the app is completely closed then the initial link is always null. Can't get logs because I have to close the app first to be able to open it like this.

**Comment by llfbandit** [comment]
The project has been refreshed. Re-run the example on Android emulator and it works fine.
