### ISSUE TITLE
uriLinkStream does not bring any event

### ISSUE THREAD

**Issue by pro100svitlo** [llfbandit/app_links#73]
**Describe the bug**

I am using `app_links: ^3.4.3` version.
Trying to listen to all new events via `appLinks.uriLinkStream`, but receive nothing.
At the same time the stream `allUriLinkStream` brings me all the clicked events.

**Does it related to**

- [ ] App Links (Android)  
- [ ] Deep Links (Android)  
- [x] Universal Links (iOS)  
- [ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

- [ ] Yes  
- [ ] No  
- [x] Irrelevant here   - **I dint get how I can test it since `example.com` is not your domain and the browser is opened**

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

- [x] Yes  
- [ ] No  
- [ ] Irrelevant here

**Comment by AlexPopaUpcode** [comment]
I am experiencing something similar, but only when users are using Chrome browser on iOS. If they are using Safari then everything works good and the app receives the events.

**Comment by pro100svitlo** [comment]
I am using the simulator for tests and Safari is used there.

**Comment by llfbandit** [comment]
`allUriLinkStream` wraps `uriLinkStream` with getInitialAppLink at preamble. This the same stream.
You can't consume twice an event.

**Comment by pro100svitlo** [comment]
>Sorry I didn't read carefully. You're issue is not on iOS but on web.

I am sorry, but I know which platform I am using and where I have a problem.
Can you please reopen the issue and investigate it?

If you need some more details from me - I can provide them.

**Comment by llfbandit** [comment]
> I am using the simulator for tests and Safari is used there.

? This is a bit misleading

**Comment by pro100svitlo** [comment]
By that in let you know which device I was using and which defaul browser is there.
But the application is flutter iOS one.

**Comment by llfbandit** [comment]
Ok, so as I said before `allUriLinkStream` wraps `uriLinkStream` with `getInitialAppLink` at preamble. Finally, this the same stream and more globally, there's only one single stream despites the four getters available.

https://github.com/llfbandit/app_links/blob/53798e5d67ebb0508e9681c8ecc3af4165a26063/lib/src/app_links_method_channel.dart#L63

But I don't understand for which use case separate streams would be useful?
