### ISSUE TITLE
All versions tested with app_links does not get initialLink or stream

### ISSUE THREAD

**Issue by reduxdj** [llfbandit/app_links#78]
I noticed in a recent build we have upgraded flutter and appLinks, what is happening for everybody on the team, is that MacOS links are completely dead, and don't work, the only thing that happens is the windows comes into focus, no errors or any output.

**Does it related to**

AppLinks: MacOS

**Does the example project work?**

[ ] Yes  
[] No  
[X ] Irrelevant here  

flutter versions this has been observed in:
```
3.13.6
3.13.5 (active)
3.10.3
3.10.0-3.0.pre
```
AppLinks versions this is observed in
```
3.4.2
3.4.3
3.4.4
3.4.5
```

https://github.com/llfbandit/app_links/assets/322547/58ed77e3-3c60-4d25-8077-73d01d2b1c05

**Comment by elvinasn** [comment]
Any updates?

**Comment by reduxdj** [comment]
Yeah, maybe they went on vacation?
