### ISSUE TITLE
Support multiple instances of app_links or passthrough unhandled links

### ISSUE THREAD

**Issue by point-source** [llfbandit/app_links#80]
### Is your feature request related to a problem? Please describe.
While using [supabase_flutter](https://pub.dev/packages/supabase_flutter), which [uses app_links to automatically handle authentication related deep links](https://github.com/supabase/supabase-flutter/blob/52a84c4db05de7735904bdb56ba118e9a26f5743/packages/supabase_flutter/lib/src/supabase_auth.dart#L282), I cannot seem to catch unrelated deep links via [auto_route](https://pub.dev/packages/auto_route) or app_links or otherwise. It seems that whatever most recently attaches as the link handler gets the links and can either act on them or discard them but not pass them along to the next handler.

### Describe the solution you'd like
Perhaps app_links can use a singleton to hold the stream and check each time an app_links instance is created / subscribed to to see if a stream already exists or if app_links is already bound to wherever it is receiving these links from (platform channel?).

This won't solve the case for auto_route because it [doesn't make use of app_links](https://github.com/Milad-Akarie/auto_route_library/blob/f4864b426167f09115ec0c8b620d419974d0b093/auto_route/lib/src/router/controller/auto_router_delegate.dart) but it would allow multiple packages to use app_links simultaneously without interference. This will likely drive adoption of app_links as a standard solution for linking.

### Describe alternatives you've considered
- Encouraging supabase_flutter to use something other than app_links in case a more native implementation (like auto_route) can provide more compatibility
- [Encouraging supabase_flutter to provide a callback which users can pass auth related deep links into once they've been filtered/handled by app_links or auto_route](https://github.com/supabase/supabase-flutter/pull/669#issuecomment-1778330334)

### Additional context
- [supabase_flutter issue #541: Allow for handling non-supabase related deep link /applink urls](https://github.com/supabase/supabase-flutter/issues/541)
- [supabase_flutter PR #605: Expose a deeplinks stream controller to allow non-supabase related deeplinks handling](https://github.com/supabase/supabase-flutter/pull/605)
- [supabase_flutter PR :669: Optionally ignore deep links](https://github.com/supabase/supabase-flutter/pull/669)
- [supabase_flutter comment mentioning creation of an app_links issue](https://github.com/supabase/supabase-flutter/pull/605#issuecomment-1725417623)
- [app_links issue #68: Ideas for v4 roadmap](https://github.com/llfbandit/app_links/issues/68)

**Comment by llfbandit** [comment]
On iOS, you can refer to custom setup for this to filter what should be be sent to Flutter app.
Otherwise, you can filter stream events on Dart side.
But there's no way, on native part, to tell that the link should not be handled. You registered at setup stage.
