### ISSUE TITLE
ERROR:R8: com.android.tools.r8.internal.XI0: Attribute InnerClasses requires EnclosingMethod attribute. Check -keepattributes directive.

### ISSUE THREAD

**Issue by ufukhawk** [llfbandit/app_links#86]
When 
`minifyEnabled true
 shrinkResources true`, the apk cannot be created.
 
 if i remove package , i can create APK file.
 
   app_links: ^3.5.0

Error : 
ERROR:R8: com.android.tools.r8.internal.XI0: Attribute InnerClasses requires EnclosingMethod attribute. Check -keepattributes directive.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:minifyProdReleaseWithR8'.
> com.android.tools.r8.CompilationFailedException: Compilation failed to complete

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by ufukhawk** [comment]
Any update ?

**Comment by llfbandit** [comment]
https://github.com/microg/SafeParcel/blob/master/safe-parcel/proguard.txt

Those rules should fix your issue.

**Comment by ufuk-sahin-alg** [comment]
@llfbandit not woking. 

    `ERROR:R8: com.android.tools.r8.internal.XI0: Attribute InnerClasses requires EnclosingMethod attribute. Check - 
    keepattributes directive.

    FAILURE: Build failed with an exception.

    * What went wrong:
     Execution failed for task ':app:minifyProdReleaseWithR8'.
      > com.android.tools.r8.CompilationFailedException: Compilation failed to complete

**Comment by llfbandit** [comment]
I guess there are missing pieces here.
I can't reproduce the issue with the example project.

Anyway, did you add at least the directive asked?
```shell
-keepattributes EnclosingMethod
```

**Comment by ufukhawk** [comment]
Thanks fixed.
