### ISSUE TITLE
Typo in docs?

### ISSUE THREAD

**Issue by AndreiMisiukevich** [llfbandit/app_links#91]
**Describe the bug**

<img width="973" alt="image" src="https://github.com/llfbandit/app_links/assets/10124814/fa2bc9c8-7373-4ef2-95d4-47adde7b908a">

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[X] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[ ] Yes  
[ ] No  
[X] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[X] Irrelevant here

**Comment by llfbandit** [comment]
No this is to illustrate when true can't be returned from the delegate, you can still handle link manually with `handleLink` method.

**Comment by animeshjain** [comment]
This was very confusing to read. Can the documentation be worded better? After reading your comment, is it correct that the following AppDelegate file will work and no change needs to be made:

```import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }
}
```
