### ISSUE TITLE
Uri.host convert to lowercase

### ISSUE THREAD

**Issue by labulakalia** [llfbandit/app_links#92]
**Describe the bug**

use this schemes `sample://foAAA/#/booAAAk/hello-deep-linking`

but get uri host is `sample://foaaa`

foAAA convert foaaa

**Does it related to**

[ ] App Links (Android)  
[ ] Deep Links (Android)  
[ ] Universal Links (iOS)  
[ ] or Custom URL schemes? (iOS)  

**Does the example project work?**

[] Yes  
[x] No  
[ ] Irrelevant here  

**Did you fully read the instructions for the targeted platform before submitting this issue?**

Uploaded your files to webserver, HTTPS, direct connection, scheme pattern setup, ...

[ ] Yes  
[ ] No  
[ ] Irrelevant here
<img width="490" alt="截屏2024-01-24 21 40 57" src="https://github.com/llfbandit/app_links/assets/24547356/7f2642dd-7c84-48e9-ad97-799fadb28168">

**Comment by llfbandit** [comment]
Thanks for the report.
You can use `string` counterparts for this case like `stringLinkStream` and so on...

This issue is due to `Uri.parse` from SDK.
