### ISSUE TITLE
Not working on android 13( im using Redmi 12 5G device)

### ISSUE THREAD

**Issue by rahulsharma9893** [llfbandit/app_links#94]
>>  my manifest.xml file
 <intent-filter>
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.BROWSABLE" />
                <category android:name="android.intent.category.DEFAULT" />

                <data android:scheme="https" />
                <data android:host="*.example.in" />
                <data android:scheme="https" />
                <data android:host=".example.in" />
                <data android:scheme="https" />
                <data android:host="example.page.link/dlink" />
                <data android:scheme="http" />
                <data android:host="*.example.in" />
                <data android:scheme="https" />
                <data android:host="example.page.link" />
                <data android:host="example.in" />
                <data android:scheme="http" />
                <data android:host="example.in" />
                <data android:scheme="https" />
            </intent-filter>
            
            
            
 >>   my myapp.dart class uses in init
            
             try {
      final _appLinks = AppLinks();
      _appLinks.allUriLinkStream.listen((uri) {
        print("initUniLinks url ${uri}");
      });
   
    } on PlatformException {
      print("initUniLinks PlatformException $PlatformException");
      // Handle exception by warning the user their action did not succeed
      // return?
    }

also package example code not working

**Comment by llfbandit** [comment]
Duplicate #65
