### ISSUE TITLE
Why not just use that metadata tag?

### ISSUE THREAD

**Issue by nhj6858mrblue** [llfbandit/app_links#98]
`<meta-data android:name-"flutter_deeplinking_enabled" android:value="true" />`
Why not just use that metadata tag?

**Comment by llfbandit** [comment]
You can but this Flutter feature is only for basic cases.
What about query parameters, other platforms, custom scheme and internal navigation with dissociation from the provided link?

**Comment by nhj6858mrblue** [comment]
There wasn't enough explanation in my question.

If you cold start your Android phone while using app_link and the corresponding metadata tag together, you will enter the screen below.
![image](https://github.com/llfbandit/app_links/assets/159093698/7f55ca0c-1097-4702-836c-2df8ab3323af)

**Comment by llfbandit** [comment]
What are you expecting by reopening this issue?
